DROP TABLE IF EXISTS favourites CASCADE;

CREATE TABLE favourites (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    dog_id INT REFERENCES dogs(id) ON DELETE CASCADE,
    liked BOOLEAN NOT NULL DEFAULT FALSE
);
